#!/usr/bin/env node
/**
 * HACK: APM can only be published via github repository. Because we use monorepo
 * approach, we can't run `apm publish` inside `atom-linter-marlint` directory.
 * The workaround for this problem is cloning placeholder repository for atom-linter-marlint,
 * copying all files inside atom-linter-marlint directory, commit those with version tag
 * specified in lerna.json, then force-push to repository then run `apm publish`
 */
const path = require('path');
const exec = require('child_process').execSync;
const version = require('../lerna.json').version;

const insidePlaceholderRepo = {
  cwd: path.join(process.cwd(), 'alm_placeholder'),
};

exec('git clone git@github.com:traveloka/atom-linter-marlint.git alm_placeholder');
exec('rm -rf "alm_placeholder/.*" 2> /dev/null');
exec('cp -R packages/atom-linter-marlint/* alm_placeholder/');
exec('cd alm_placeholder');
exec('git add -A', insidePlaceholderRepo);
exec(`git commit -m "v${version}"`, insidePlaceholderRepo);
exec(`git tag "v${version}"`, insidePlaceholderRepo);
exec('git push origin master --follow-tags --force', insidePlaceholderRepo);
exec(`apm publish --tag "v${version}"`, insidePlaceholderRepo);
exec('rm -rf alm_placeholder');
